### DISCUSSION TITLE
v5.1.0

### DISCUSSION THREAD

**Discussion by J12934** [juice-shop/multi-juicer#126] [Releases]
## 🚀 Features

- Update default Juice Shop version to v14.1.1 (fbf81100409394c6e73fcbb94caf710aedd3a822)

## 🐛 Bug Fixes

- Fix Missing Challenge Id in score-board and ProgressWatchdog @shipko (#124)

## 📚 Docs

- Add `https` Section to Azure Setup Guide @sydseter (#118)

## 📌 Dependencies

- Bump got from 11.8.2 to 11.8.5 in juice-balancer & cleaner @dependabot (#121, #122)

<hr /><em>This discussion was created from the release <a href='https://github.com/iteratec/multi-juicer/releases/tag/v5.1.0'>v5.1.0</a>.</em>

**Comment by T0hha** [comment]
Hi @J12934,
I've just installed the latest version of multi-juicer to OpenShift 4 using helm and when I try to register a new team I get following error:

time="2023-01-30T15:55:16.319Z" level="info" msg="Creating JuiceShop Deployment for team 'test'"
time="2023-01-30T15:55:16.423Z" level="error" msg="Error while creating deployment or service for team test"
time="2023-01-30T15:55:16.423Z" level="error" msg="deployments.apps "t-test-juiceshop" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"

Do you know how can I fix it?

Thanks in advance.

**Reply by T0hha** [reply]
OK, that issue was solved by setting skipOwnerReference: true
So now juice-shop container is being created but I get another error:

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v16.17.0 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Configuration multi-juicer validated (OK)
info: Entity models 19 of 19 are initialized (OK)
node:fs:2852
handleErrorFromBinding(ctx);
^
Error: EACCES: permission denied, copyfile 'data/static/botDefaultTrainingData.json' -> 'data/chatbot/botDefaultTrainingData.json'
at Object.copyFileSync (node:fs:2852:3)
at initialize (/juice-shop/build/routes/chatbot.js:27:8)
at Object.<anonymous> (/juice-shop/build/routes/chatbot.js:35:6)
at Module._compile (node:internal/modules/cjs/loader:1126:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
at Module.load (node:internal/modules/cjs/loader:1004:32)
at Function.Module._load (node:internal/modules/cjs/loader:839:12)
at Module.require (node:internal/modules/cjs/loader:1028:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/juice-shop/build/server.js:113:17)
at Module._compile (node:internal/modules/cjs/loader:1126:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
at Module.load (node:internal/modules/cjs/loader:1004:32)
at Function.Module._load (node:internal/modules/cjs/loader:839:12)
at Module.require (node:internal/modules/cjs/loader:1028:19)
at require (node:internal/modules/cjs/helpers:102:18)
at /juice-shop/build/app.js:7:20
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
errno: -13,
syscall: 'copyfile',
code: 'EACCES',
path: 'data/static/botDefaultTrainingData.json',
dest: 'data/chatbot/botDefaultTrainingData.json'
}

Any hints how to fix it?

**Reply by J12934** [reply]
Hi @T0hha 

you should have two options:

1. Run MultiJuicer without ownerReferences by setting `balancer.skipOwnerReference=true` on install. `helm install <release-name> multi-juicer/multi-juicer --set "balancer.skipOwnerReference=true"`
2. I think with OpenShift 4 it should be possible to add the necessary RBAC rules on it to actually allow with ownerReferences. The following should hopefully add the missing RBAC permissions. Would be cool if you could test if this works. We could probably just add this to the helm chart if this lets MultiJuicer run on OpenShift by default.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: juice-balancer-openshift-patch
rules:
  - apiGroups: ['apps']
    resources: ['deployments/finalizers']
    verbs: ['*']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pods/finalizers']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juice-balancer-openshift-patch
subjects:
  - kind: ServiceAccount
    name: juice-balancer
roleRef:
  kind: Role
  name: juice-balancer-openshift-patch
  apiGroup: rbac.authorization.k8s.io

```
