### ISSUE TITLE
Custom Balancer Logo

### ISSUE THREAD

**Issue by Ak-wa** [juice-shop/multi-juicer#222]
Hi, im trying to change the MultiJuicer Logo at initial "Getting Started" page where users can create a team.

The logo & favicon I added in values.yaml works - but only on the authenticated shop page, not at the landing page for creating a team.

![multijuice_issue](https://github.com/juice-shop/multi-juicer/assets/44728139/6fbf926d-8f59-4696-a2a8-eebeaf963c10)

Im launching Multijuicer via the following command
`helm install -f values.yaml multi-juicer ./multi-juicer/helm/multi-juicer/`

with content of values.yaml:
```
...
config: |
    application:
      logo: https://url-to-my-logo.svg
      favicon: https://url-to-my-favicon.ico


      showVersionNumber: false
...
```

How do i make the Multijuicer Balancer use my own logo?
