### ISSUE TITLE
Cannot create Team on OpenShift 4.11.59

### ISSUE THREAD

**Issue by bastien-reinhardt** [juice-shop/multi-juicer#223]
## Expected Behavior

Follow installation guide for Openshift and Multi-Juicer should work.

## Current Behavior

Follow installation guide.
"Step: Creating a Team" does not work.

JuiceBalancer Pod Logs:
time="2024-05-31T07:47:47.425Z" level="info" msg="JuiceBalancer listening on port 3000!"
time="2024-05-31T07:50:20.649Z" level="info" msg="Team test doesn't have a JuiceShop deployment yet"
time="2024-05-31T07:50:20.741Z" level="info" msg="Reached 0/10 instances"
time="2024-05-31T07:50:23.533Z" level="info" msg="Creating JuiceShop Deployment for team 'test'"
time="2024-05-31T07:50:23.723Z" level="error" msg="Error while creating deployment or service for team test"
time="2024-05-31T07:50:23.723Z" level="error" msg="deployments.apps "t-test-juiceshop" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"

## Possible Solution

This solution works for me.
As per [RedHat Solution](https://access.redhat.com/solutions/5372461) add the "update" verb to the "deployments/finalizers" ressources on the "juice-balancer" namespace role.
The role should look like this:
```yaml
rules:
  - verbs:
      - get
      - create
      - list
      - delete
      - patch
      - update
    apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
  - verbs:
      - get
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - get
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - pods
```

I hope this helps others :)

Cheers
