### ISSUE TITLE
Hints not shown in CTF mode

### ISSUE THREAD

**Issue by turban1988** [juice-shop/multi-juicer#271]
Dear all,

I am using multi juicer to organize a small CTF. However, when starting multi juicer, no hints are shown on the score board.

I am using the default config (`values.yaml`)

```
 config:
      application:
        logo: https://raw.githubusercontent.com/juice-shop/multi-juicer/main/images/multijuicer-icon-only-padding.png
        favicon: https://raw.githubusercontent.com/juice-shop/multi-juicer/main/balancer/ui/public/favicon.ico
        showVersionNumber: false
        showGitHubLinks: false
      challenges:
        showHints: true
      hackingInstructor:
        isEnabled: true
      ctf:
        showFlagsInNotifications: false
    # -- Specify a custom NODE_ENV for JuiceShop. If value is changed to something other than 'multi-juicer' it's not possible to set a custom config via `juiceShop.config`.
    nodeEnv: "ctf"
```
I also tried to add `insertHints: free` to the file without any effect.

What am I missing?
